### ISSUE TITLE
[metrics] pipermail raw data

### ISSUE THREAD

**Issue by vchrombie** [vchrombie/gsoc#11]
Opening this issue to discuss the possible metrics which can be extracted from the pipermail raw data for `pipermailqm` enricher.

**Comment by valeriocos** [comment]
What do you think about the following metrics?
- number of emails
- number of replies (maybe this can be difficult to calculate)
- number of threads (maybe this can be difficult to calculate)
- number of users

**Comment by vchrombie** [comment]
Thanks for the suggestions @valeriocos 

>     * number of emails
>     * number of users

Okay!


>     * number of replies (maybe this can be difficult to calculate)
>     * number of threads (maybe this can be difficult to calculate)

I will try to implement and let you know how it goes.

**Comment by valeriocos** [comment]
ok, thanks @vchrombie

**Comment by vchrombie** [comment]
planned metrics are implemented, so closing this issue
feel free to open if you have any more metric suggestions in the future
