### ISSUE TITLE
[metrics] meetup raw data

### ISSUE THREAD

**Issue by vchrombie** [vchrombie/gsoc#14]
Opening this issue to discuss the possible metrics which can be extracted from the meetup raw data for _meetupqm_ enricher.

**Comment by valeriocos** [comment]
Hi @vchrombie ,

What do you think about the following metrics?
- number of RSVPS
- number of comments
- number of topics
- number of users per meetup group

**Comment by vchrombie** [comment]
Hi @valeriocos, sorry for the late reply.

I have some doubts and would like to define these metrics more clearly.

>     * number of RSVPS
>     * number of comments

these two metrics can be defined as per day like number os RSVPS per day and number of comments per day, perfect

>     * number of topics
>     * number of users per meetup group

I was wondering how can we implement these. The both metrics would be a number. Did I miss anything?

**Comment by valeriocos** [comment]
No worries @vchrombie 

> these two metrics can be defined as per day like number os RSVPS per day and number of comments per day, perfect

perfect!

> I was wondering how can we implement these. The both metrics would be a number. Did I miss anything?

- Topics are already available in the raw data: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/meetup.py#L241

- The group members info is also available in the raw data: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/meetup.py#L248

Do the pointers above help with clarifying how to implement these metrics?

**Comment by vchrombie** [comment]
Hi @valeriocos, thanks for the reply.

>     * Topics are already available in the raw data: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/meetup.py#L241
>     * The group members info is also available in the raw data: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/meetup.py#L248

Ya, I know that they exist in the raw data. Sorry for not being clear with the doubt. I was asking something different.

I meant that these metrics (number of topics and number of users per meetup group) wouldn't go like the other metrics which are defined per day as the number of RSVPs per day. I felt 'number of topics created per day' doesn't sound interesting and at the same time, they cannot be extracted as we don't have any datetime field in that.

I was asking if the number of topics is just a number, not like a 'per day'. It can be 'per event'. :thinking: 

Let me know if it is still not clear.

**Comment by valeriocos** [comment]
I see, thank you for the clarification @vchrombie. 

> I was asking if the number of topics is just a number, not like a 'per day'. It can be 'per event'.

Probably these metrics cannot be calculated with the current data, it seems that topics and group members show only their last values. Thus, even if we calculate them 'per event', we can see a difference in these metrics only when getting incremental data (not on the first collection). We could discard these metrics, wdyt?

What about having a metric that uses `yes_rsvp_count` (see example below), basically the people who plan to attend the meetup? In this case, it could be 'per event'. 

I understand that 'per event' metrics should be used with caution in a quality model, since they would make sense only if we consider the average/median of their values, does it make sense?

```
"rsvp_limit": 65,
        "rsvpable": false,
        "rsvps": [
            {
                "created": 1565781589000,
                "event": {
                    "id": "263974680",
                    "name": "Meetup Gitlab Curitiba",
                    "time": 1568671200000,
                    "utc_offset": -10800000,
                    "yes_rsvp_count": 65 <-------
                },
                "group": {
                    "group_photo": {
                        "base_url": "https://secure.meetupstatic.com",
                        "highres_link": "https://secure.meetupstatic.com/photos/event/2/f/d/c/highres_483852252.jpeg",
                        "id": 483852252,
                        "photo_link": "https://secure.meetupstatic.com/photos/event/2/f/d/c/600_483852252.jpeg",
                        "thumb_link": "https://secure.meetupstatic.com/photos/event/2/f/d/c/thumb_483852252.jpeg",
                        "type": "event"
                    },
                    "id": 32557004,
                    "join_mode": "open",
                    "localized_location": "Curitiba, Brazil",
                    "members": 332,
                    "name": "GitLab Curitiba",
                    "status": "active",
                    "urlname": "GitLab-Curitiba",
                    "who": "Membros"
                },
                "guests": 0,
                "member": {
                    "event_context": {
                        "host": false
                    },
                    "id": 268304512,
                    "name": "ademilson carvalho"
                },
                "response": "yes",
                "updated": 1565781589000,
                "venue": {
                    "address_1": "R. Nunes Machado, 68",
                    "city": "Curitiba",
                    "country": "br",
                    "id": 26553228,
                    "lat": -25.43813705444336,
                    "localized_country_name": "Brazil",
                    "lon": -49.27540969848633,
                    "name": "Rentcars.com",
                    "repinned": true
                }
            },
```

**Comment by vchrombie** [comment]
Hi @valeriocos 

> Probably these metrics cannot be calculated with the current data, it seems that topics and group members show only their last values. Thus, even if we calculate them 'per event', we can see a difference in these metrics only when getting incremental data (not on the first collection). We could discard these metrics, wdyt?

Yes, I agree with you.


> What about having a metric that uses `yes_rsvp_count` (see example below), basically the people who plan to attend the meetup? In this case, it could be 'per event'.

I got it. The metric _number of yes rsvp_ seems good to me.

> I understand that 'per event' metrics should be used with caution in a quality model, since they would make sense only if we consider the average/median of their values, does it make sense?

True, I understand the point. Also, I had one doubt. What datetime should be good to use in this metric?

Right now, we have `created` (when the meetup event is created) and `time` (actual event). I am a bit confused between these two. But, I'm a bit aligned towards the date of the actual event. Do you have any comments?

```
"rsvp_limit": 65,
        "rsvpable": false,
        "rsvps": [
            {
                "created": 1565781589000, <--------
                "event": {
                    "id": "263974680",
                    "name": "Meetup Gitlab Curitiba",
                    "time": 1568671200000, <--------
                    "utc_offset": -10800000,
                    "yes_rsvp_count": 65 
                },
```

**Comment by valeriocos** [comment]
The actual event data looks better and makes much more sense

**Comment by vchrombie** [comment]
planned metrics are implemented, so closing this issue
feel free to open if you have any more metric suggestions in the future
