### ISSUE TITLE
Implement tests for the enrichers

### ISSUE THREAD

**Issue by vchrombie** [vchrombie/gsoc#15]
Opening this issue for any discussion or questions regarding the tests for the enrichers.

**Comment by valeriocos** [comment]
@vchrombie I would suggest to take a look to the tests for the SCMS enrichers (https://github.com/chaoss/grimoirelab-elk/pull/887), thanks. Let me know if you need any clarification or you (fore)see blockers

**Comment by vchrombie** [comment]
The work will be continued at [glab-prosoul/grimoirelab-elk](https://github.com/glab-prosoul/grimoirelab-elk).
