### ISSUE TITLE
[enricher] discussion about what to use for project item

### ISSUE THREAD

**Issue by vchrombie** [vchrombie/gsoc#18]
opening this issue, in reply to @valeriocos's comment in https://github.com/vchrombie/gsoc/issues/13#issuecomment-668750306.

> Hi @vchrombie, the problem may be related to the fact that some raw items have been generated before [chaoss/grimoirelab-perceval@9b5a7ac](https://github.com/chaoss/grimoirelab-perceval/commit/9b5a7accfd2824e2e0cc917ac8f968ba0c2db4f6), which introduced the attribute "search_fields".
> 
> We had a conversation time ago about using the attribute "origin" instead of "search_fields". If this is still not possible, a workaround is to modify the raw items to include the search_fields (it could be achieved with an update_by_query), wdyt?

I solved the issue, used the `origin` to derive the project for the current scenario, but I would like to discuss the possible workaround and also over the implementation too.

**Comment by vchrombie** [comment]
We had a small chat earlier of using `search_fields` but not only `origin`. I'll first explain the problem regarding it.

Let's take the gitlab example

Perceval item would look something like this
```
    "origin": "https://gitlab.com/Bitergia/devops%2Findexwarrior",
    "perceval_version": "0.16.0",
    "search_fields": {
        "groups": [
            "devops"
        ],
        "iid": 2,
        "item_id": "10358778",
        "owner": "Bitergia",
        "project": "indexwarrior"
    },
```

So, if we consider the `origin` for the project item
```
    def extract_project(self, item):
        return item['origin']
```
project: https://gitlab.com/Bitergia/devops%2Findexwarrior

When we create assessments, the CSV files are generated with the project name as the file name, like `project_csv.csv`. Here in this case, it would create `https://gitlab.com/Bitergia/devops%2Findexwarrior_csv.csv`, so this ends up in an error as it looks for folders. It assumes the `/` as the path where the CSV should be saved and gitlab.com, Bitergia as folders.

So, I opted for `search_fields` to 
```
    def extract_project(self, item):
        return item['search_fields']['project']
```
project: indexwarrior

CSV files would be saved as `indexwarrior.csv`

This is the scenario, we can still opt for `origin` to produce similar result, but we might need to use regex and deduce it and it is not at all a problem. I can do that as well.

**Comment by vchrombie** [comment]
Also, this depends on the data source too.

Pipermail scenario



```
    "origin": "https://lists.linuxfoundation.org/pipermail/grimoirelab-discussions/",
    "perceval_version": "0.16.0",
    "search_fields": {
        "item_id": "<CAFEYM2uF=mj4ALb4RLRPWCw7Psv0BavhA5b9AR8=UgWz0zF7yw@mail.gmail.com>"
    },
```

We don't have any `search_fields` item, so using `origin` but I trimmed it.
```
    def extract_project(self, item):
        return item['origin'].split('/')[-2]
```

**Comment by vchrombie** [comment]
Meetup is again different

```
    "origin": "https://meetup.com/",
    "perceval_version": "0.16.0",
    "search_fields": {
        "group_id": 30080624,
        "group_name": "Official GitLab Meetups ANZ",
        "item_id": "270157320"
    },
```

There is an `origin` field but it is only "https://meetup.com/". So, we can't really use it in anyway. I'm using the `search_field` here.
```
    def extract_project(self, item):
        return item['search_fields']['group_name']
```

**Comment by vchrombie** [comment]
Git is similar to Pipermail

```
    "origin": "https://gitlab.com/Bitergia/devops/indexwarrior.git",
    "perceval_version": "0.16.0",
    "search_fields": {
        "item_id": "b0de2636811d356bb62573e3154ea0a6556211a1"
    },
```
Using `origin` and reducing to the result.
```
    def extract_project(self, item):
        return re.findall(URL_PATTERN, item['origin'])[0][-1]
```

**Comment by vchrombie** [comment]
Sorry for the really long thread, but I would be interested to know your opinions on this. I feel it is good to use only one item, either `origin` or `search_fields`. But yea, depending on the data source, we can change too.

**Comment by vchrombie** [comment]
> Hi @vchrombie, the problem may be related to the fact that some raw items have been generated before chaoss/grimoirelab-perceval@9b5a7ac, which introduced the attribute "search_fields".

Talking about this, I would be interested to update the raw data because it might be problematic in future too.

> If this is still not possible, a workaround is to modify the raw items to include the search_fields (it could be achieved with an update_by_query), wdyt?

@valeriocos, do you have any pointers for this or let me know if I have to look anywhere for this. I'm interested to learn and try this. It might be useful sometime in future.

**Comment by valeriocos** [comment]
> do you have any pointers for this or let me know if I have to look anywhere for this. I'm interested to learn and try this. It might be useful sometime in future.

Update_by_query can be used to update the docs:
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/docs-update-by-query.html. You can combine it with painless code: 
https://www.elastic.co/guide/en/elasticsearch/painless/6.8/painless-examples.html. You can either execute the query from the dev tools of Kibiter or via a Python script

**Comment by vchrombie** [comment]
closing the issue as we have come to a decision

if `search_fields` is applicable then `search_fields` else `origin`
