### ISSUE TITLE
Project Documentation

### ISSUE THREAD

**Issue by vchrombie** [vchrombie/gsoc#20]
Opening this issue to discuss about the work on the documentation required for the project.

**Comment by vchrombie** [comment]
One good starting point would be [Bitergia/prosoul](https://github.com/Bitergia/prosoul/).

Now that we have a workflow with Prosoul and GrimoireLab, we can include the information replacing the old one, here at https://github.com/Bitergia/prosoul/tree/master/doc.
We can update the architecture and workflow diagram too. I have them. @valeriocos helped with these diagrams. :smile: 

WRT GrimoireLab, the configurations of the enrichers should be updated in [chaoss/grimoirelab-sirmordred](https://github.com/chaoss/grimoirelab-sirmordred). I will open a new PR for this.

Do you think we should add some reference or more details regarding the Quality Models or its bunch of enrichers other than these? 
Let me know if you have any more suggestions.

**Comment by valeriocos** [comment]
> Do you think we should add some reference or more details regarding the Quality Models or its bunch of enrichers other than these?
Let me know if you have any more suggestions

What do you think about adding a README.md in the qm folders within ELK?

**Comment by vchrombie** [comment]
Hi @valeriocos 

> What do you think about adding a README.md in the qm folders within ELK?

That sounds awesome. Do you have anything specific you would be interested to have in the README.md?

**Comment by vchrombie** [comment]
https://github.com/Bitergia/prosoul/pull/216

[glab-prosoul/prosoul](https://github.com/glab-prosoul/prosoul)
