### ISSUE TITLE
[metrics] gitlab raw data

### ISSUE THREAD

**Issue by vchrombie** [vchrombie/gsoc#8]
Opening this issue to discuss the possible metrics which can be extracted from the gitlab raw data for `gitlabqm` enricher.

**Comment by vchrombie** [comment]
List of metrics which were proposed in the earlier meeting by @valeriocos
- number of issues per day
- number of comments per day
- number of merges per day

**Comment by vchrombie** [comment]
Hi @valeriocos 

I was thinking of what all metrics can be defined from gitlab data. 

> number of issues per day

Can we make this metric into two with much more clear meaning like 
- number of issues opened per day
- number of issues closed per day

We can use them in the QMs too.

WDYT?
@Polaris000 @inishchith @dlumbrer

**Comment by valeriocos** [comment]
+1, thanks

**Comment by Polaris000** [comment]
Sounds good!

**Comment by inishchith** [comment]
Sounds good @vchrombie

**Comment by dlumbrer** [comment]
+1 here as well :-)  @vchrombie

**Comment by vchrombie** [comment]
I have implemented the issue related metrics.

> * number of issues opened per day
> 
> * number of issues closed per day


I think we can do the same thing for merge requests too

> number of merges per day

* number of mrs opened in a day
* number of mrs merged in a day
* number of mrs closed in a day

**Comment by vchrombie** [comment]
> number of comments per day

I left this at that time, but I'll complete it by the next PR.

**Comment by vchrombie** [comment]
> number of comments per day

do you think we need to consider the comments as two different entities like `issue_comments` and `merge_comments`?

I was thinking it would be better if we can keep them separate as we can specifically use `numberIssueComments` and `numberMergeComments` as metrics in the quality models if needed.

**Comment by valeriocos** [comment]
Yes, good idea! let's keep them separated for the moment.

**Comment by vchrombie** [comment]
> I was thinking it would be better if we can keep them separate as we can specifically use `numberIssueComments` and `numberMergeComments` as metrics in the quality models if needed.

I have completed working on this. I will add them to the PR.

Also, I was going through the existing quality models, I saw one different metric in the Developer QM. It is the "number of issues attended". I think this has a different meaning than the number of comments. The `numberIssueComments` means the total number of comments across all issues on a particular day whereas the `numberIssuesAttended` would become the number of issues that have at least one comment on a particular date. This should be easy to implement.

Do you have any comments on this?

**Comment by valeriocos** [comment]
> the numberIssuesAttended would become the number of issues that have at least one comment on a particular date. This should be easy to implement.

It should be the number of issues that have at least one comment, which is not written by the issue reporter, wdyt?

**Comment by vchrombie** [comment]
> It should be the number of issues that have at least one comment, which is not written by the issue reporter, wdyt?

ah yes, that makes the definition more clear
thanks @valeriocos

**Comment by valeriocos** [comment]
you're welcome @vchrombie

**Comment by vchrombie** [comment]
planned metrics are implemented, so closing this issue
feel free to open if you have any more metric suggestions in the future
