### ISSUE TITLE
[metrics] git raw data

### ISSUE THREAD

**Issue by vchrombie** [vchrombie/gsoc#9]
Opening this issue to discuss the possible metrics which can be extracted from the git raw data for `gitqm` enricher.

**Comment by valeriocos** [comment]
Possible metrics:
- number of commits
- number of files in commits

wdyt?

**Comment by vchrombie** [comment]
Hi @valeriocos 
Sorry for the late reply.

>     * number of commits

yes, this is good to go, number of commits per day 
I started working on this. You can expect a PR soon.

>     * number of files in commits

is it like the number of files changed per day or am I missing something?

**Comment by valeriocos** [comment]
No worries @vchrombie

> is it like the number of files changed per day or am I missing something?

It can be either the number of unique files changed per day or all files that changed at least once in a day.

Other metrics could be:
- the sum of the additions/deletions per day (this information is available in the raw data: https://github.com/chaoss/grimoirelab-elk/blob/master/tests/data/git.json#L28)
- the number of actions per day (see https://github.com/chaoss/grimoirelab-elk/blob/master/tests/data/git.json#L41)

**Comment by vchrombie** [comment]
> It can be either the number of unique files changed per day or all files that changed at least once in a day.

Okay. I will try the implementation and let you know.

> Other metrics could be:
> 
>     * the sum of the additions/deletions per day (this information is available in the raw data: https://github.com/chaoss/grimoirelab-elk/blob/master/tests/data/git.json#L28)
> 
>     * the number of actions per day (see https://github.com/chaoss/grimoirelab-elk/blob/master/tests/data/git.json#L41)

These two metrics look good too @valeriocos. I will add them.

**Comment by vchrombie** [comment]
Hi @valeriocos 
I had a doubt regarding the actions metric

```
"files": [
    {
        "action": "M",
        "added": "3",
        "file": "README.md",
        "indexes": [
            "5c31153",
            "0c22d06"
        ],
        "modes": [
            "100644",
            "100644"
        ],
        "removed": "0"
    },
    {
        "action": "A",
        "added": "-",
        "file": "work/week-3/dashboard-1.png",
        "indexes": [
            "0000000",
            "f5c6830"
        ],
        "modes": [
            "000000",
            "100644"
        ],
        "removed": "-"
    },
    {
        "action": "A",
        "added": "-",
        "file": "work/week-3/dashboard-2.png",
        "indexes": [
            "0000000",
            "199e3e8"
        ],
        "modes": [
            "000000",
            "100644"
        ],
        "removed": "-"
    },
    {
        "action": "A",
        "added": "-",
        "file": "work/week-3/dashboard-3.png",
        "indexes": [
            "0000000",
            "53a67c3"
        ],
        "modes": [
            "000000",
            "100644"
        ],
        "removed": "-"
    }
],
```

so, should we count the number of unique actions (here, it will be 2) or just number of actions (here, it will be 4)?

**Comment by valeriocos** [comment]
Hi @vchrombie , I would go for the number of actions (4) since it gives insights on the activity over file. Do you have some scenario in mind where the unique actions could be useful?

**Comment by vchrombie** [comment]
> Hi @vchrombie , I would go for the number of actions (4) since it gives insights on the activity over file. 

perfect, in fact, this is easy to implement

> Do you have some scenario in mind where the unique actions could be useful?

first of all, I didn't understand the term :sweat_smile: 
what does the term 'action' define here?

sorry, I was lost somewhere and edited your previous comment :sweat_smile:

**Comment by valeriocos** [comment]
ehehe no worries!

Actions are the changes done on a file, A stands for added, D for deleted, etc.. (see https://linux.die.net/man/1/git-log look for ` Added (A)`).

**Comment by vchrombie** [comment]
> Actions are the changes done on a file, A stands for added, D for deleted, etc.. (see https://linux.die.net/man/1/git-log look for ` Added (A)`).

Ahh, nice. I never heard of it till now. Thanks @valeriocos 

> Do you have some scenario in mind where the unique actions could be useful?

I don't think so, I agree the total number of actions would be better than unique actions.

**Comment by valeriocos** [comment]
You're welcome!

**Comment by vchrombie** [comment]
planned metrics are implemented, so closing this issue
feel free to open if you have any more metric suggestions in the future
